tosca_definitions_version: tosca_simple_yaml_1_2

description: Sample Private registry VNF

imports:
  - etsi_nfv_sol001_common_types.yaml
  - etsi_nfv_sol001_vnfd_types.yaml
  - sample_vnfd_types.yaml

topology_template:
  inputs:
    id:
      type: string
    vendor:
      type: string
    version:
      type: version
    descriptor_id:
      type: string
    descriptor_version:
      type: string
    provider:
      type: string
    product_name:
      type: string
    software_version:
      type: string
    vnfm_info:
      type: list
      entry_schema:
        type: string
    flavour_id:
      type: string
    flavour_description:
      type: string

  substitution_mappings:
    node_type: company.provider.VNF
    properties:
      flavour_id: simple
    requirements:
      virtual_link_external: [ CP1, virtual_link ]

  node_templates:
    VNF:
      type: company.provider.VNF
      properties:
        flavour_description: A simple flavour
      interfaces:
        Vnflcm:
          instantiate_end:
            implementation: mgmt-drivers-private-registry
          heal_end:
            implementation: mgmt-drivers-private-registry
      artifacts:
        mgmt-drivers-private-registry:
          description: Management driver for Docker private registry
          type: tosca.artifacts.Implementation.Python
          file: Scripts/private_registry_mgmt.py

    PrivateRegistryVDU:
      type: tosca.nodes.nfv.Vdu.Compute
      properties:
        name: PrivateRegistryVDU
        description: Private registry compute node
        vdu_profile:
          min_number_of_instances: 1
          max_number_of_instances: 1
        sw_image_data:
          name: Image for Private registry
          version: '20.04'
          checksum:
            algorithm: sha-512
            hash: fb1a1e50f9af2df6ab18a69b6bc5df07ebe8ef962b37e556ce95350ffc8f4a1118617d486e2018d1b3586aceaeda799e6cc073f330a7ad8f0ec0416cbd825452
          container_format: bare
          disk_format: qcow2
          min_disk: 0 GB
          size: 2 GB

      artifacts:
        sw_image:
          type: tosca.artifacts.nfv.SwImage
          file: ../Files/images/ubuntu-20.04-server-cloudimg-amd64.img

      capabilities:
        virtual_compute:
          properties:
            virtual_memory:
              virtual_mem_size: 4 GB
            virtual_cpu:
              num_virtual_cpu: 2
            virtual_local_storage:
              - size_of_storage: 45 GB

    CP1:
      type: tosca.nodes.nfv.VduCp
      properties:
        layer_protocols: [ ipv4 ]
        order: 0
      requirements:
        - virtual_binding: PrivateRegistryVDU
