---
- name: install python and libs
  become: yes
  apt: name={{ item }} update_cache=yes
  with_items:
      - python3
      - python3-dev
      - python3-pip

- name: install git tools
  become: yes
  apt: name={{ item }}
  with_items:
      - git
      - git-review

- name: install networking tools
  become: yes
  apt: name={{ item }}
  with_items:
      - bridge-utils

- name: upgrade apt packages
  become: yes
  apt:
      upgrade: safe
