- nodeset:
    name: openstack-4-nodes-focal
    nodes:
      - name: controller
        label: ubuntu-focal
      - name: controller-tacker
        label: ubuntu-focal
      - name: compute1
        label: ubuntu-focal
      - name: compute2
        label: ubuntu-focal
    groups:
      # Nodes running the compute service
      - name: compute
        nodes:
          - compute1
          - compute2
      # Nodes that are not the controller
      - name: subnode
        nodes:
          - controller-tacker
          - compute1
          - compute2
      # Switch node for multinode networking setup
      - name: switch
        nodes:
          - controller
      # Peer nodes for multinode networking setup
      - name: peers
        nodes:
          - controller-tacker
          - compute1
          - compute2

- job:
    name: tacker-functional-devstack-multinode-legacy
    parent: devstack
    description: |
      Base multinodes job for devstack-based functional tests
    nodeset: openstack-4-nodes-focal
    pre-run: playbooks/devstack/pre.yaml
    run: playbooks/devstack/run.yaml
    post-run: playbooks/devstack/post.yaml
    roles:
      - zuul: openstack-infra/devstack
    timeout: 10800
    required-projects:
      - openstack/cinder
      - openstack/glance
      - openstack/keystone
      - openstack/neutron
      - openstack/nova
      - openstack/placement
      - openstack/aodh
      - openstack/blazar
      - openstack/blazar-nova
      - openstack/horizon
      # Temporarily remove because of Ubuntu Focal Migration issue
      #   https://storyboard.openstack.org/#!/story/2007732
      # - openstack/barbican
      # Temporarily remove because of Ubuntu Focal Migration issue
      #   https://storyboard.openstack.org/#!/story/2008121
      #   https://review.opendev.org/#/c/752294/
      # - openstack/ceilometer
      - openstack/heat
      - openstack/mistral
      - openstack/mistral-dashboard
      - openstack/networking-sfc
      # Temporarily remove because of Ubuntu Focal Migration issue
      #   https://storyboard.openstack.org/#!/story/2008121
      #   https://review.opendev.org/#/c/752294/
      # - openstack/python-barbicanclient
      - openstack/python-blazarclient
      - openstack/python-mistralclient
      - openstack/python-tackerclient
      - openstack/tacker
      - openstack/tacker-horizon
      - x/fenix
    vars:
      devstack_localrc:
        CELLSV2_SETUP: singleconductor
        PHYSICAL_NETWORK: mgmtphysnet0
        OVS_BRIDGE_MAPPINGS: public:br-ex,mgmtphysnet0:br-infra
        Q_DVR_MODE: dvr
        DATABASE_TYPE: mysql
        KEYSTONE_SERVICE_HOST: "{{ hostvars['controller']['nodepool']['private_ipv4'] }}"
        MYSQL_HOST: "{{ hostvars['controller']['nodepool']['private_ipv4'] }}"
        TACKER_HOST: "{{ hostvars['controller-tacker']['nodepool']['private_ipv4'] }}"
        TACKER_MODE: standalone
        IS_ZUUL_FT: True
        Q_SERVICE_PLUGIN_CLASSES: router,neutron.services.metering.metering_plugin.MeteringPlugin,networking_sfc.services.flowclassifier.plugin.FlowClassifierPlugin,neutron.services.qos.qos_plugin.QoSPlugin,qos
        Q_ML2_PLUGIN_EXT_DRIVERS: port_security,qos
        L2_AGENT_EXTENSIONS: qos
      devstack_local_conf:
        post-config:
          $NEUTRON_DHCP_CONF:
            DEFAULT:
              enable_isolated_metadata: True
      test_matrix_configs: [neutron]
      zuul_work_dir: src/opendev.org/openstack/tacker
    host-vars:
      controller:
        devstack_plugins:
          heat: https://opendev.org/openstack/heat
          networking-sfc: https://opendev.org/openstack/networking-sfc
          aodh: https://opendev.org/openstack/aodh
          # Temporarily remove because of Ubuntu Focal Migration issue
          #   https://storyboard.openstack.org/#!/story/2008121
          #   https://review.opendev.org/#/c/752294/
          # ceilometer: https://opendev.org/openstack/ceilometer
          # Temporarily remove because of Ubuntu Focal Migration issue
          #   https://storyboard.openstack.org/#!/story/2007732
          # barbican: https://opendev.org/openstack/barbican
          mistral: https://opendev.org/openstack/mistral
          blazar: https://opendev.org/openstack/blazar
          fenix: https://opendev.org/x/fenix
        devstack_services:
          # Core services enabled for this branch.
          # This list replaces the test-matrix.
          # Shared services
          mysql: true
          rabbit: true
          tls-proxy: false
          # Keystone services
          key: true
          # Glance services
          g-api: true
          # Nova services
          n-api: true
          n-api-meta: true
          n-cond: true
          n-cpu: false
          n-novnc: true
          n-sch: true
          placement-api: true
          # Neutron services
          # We need to keep using the neutron-legacy based services for
          # now until all issues with the new lib/neutron code are solved
          q-agt: true
          q-dhcp: true
          q-l3: true
          q-meta: true
          q-metering: true
          q-svc: true
          q-qos: true
          # Cinder services
          c-api: true
          c-sch: true
          c-vol: true
          cinder: true
          # Services we don't need.
          # This section is not really needed, it's for readability.
          horizon: false
          tempest: false
          swift: false
          s-account: false
          s-container: false
          s-object: false
          s-proxy: false
          c-bak: false
        tox_install_siblings: false
      controller-tacker:
        devstack_local_conf: {}
        devstack_services:
          q-agt: true
          # Tacker services
          tacker: true
          tacker-conductor: true
        devstack_plugins:
          # Temporarily remove because of Ubuntu Focal Migration issue
          #   https://storyboard.openstack.org/#!/story/2008121
          #   https://review.opendev.org/#/c/752294/
          # ceilometer: https://opendev.org/openstack/ceilometer
          tacker: https://opendev.org/openstack/tacker
        tox_envlist: dsvm-functional-legacy
    group-vars:
      subnode:
        devstack_localrc:
          CELLSV2_SETUP: singleconductor
          PHYSICAL_NETWORK: mgmtphysnet0
          OVS_BRIDGE_MAPPINGS: public:br-ex,mgmtphysnet0:br-infra
          Q_DVR_MODE: dvr
          DATABASE_TYPE: mysql
          KEYSTONE_SERVICE_HOST: "{{ hostvars['controller']['nodepool']['private_ipv4'] }}"
          MYSQL_HOST: "{{ hostvars['controller']['nodepool']['private_ipv4'] }}"
          TACKER_HOST: "{{ hostvars['controller-tacker']['nodepool']['private_ipv4'] }}"
          TACKER_MODE: standalone
          IS_ZUUL_FT: True
        # Since a VirtualInterfaceCreateException occurs during a test,
        # the setting of network-vif-plugged is changed by the reference of
        # the following URL.
        #   https://bugs.launchpad.net/heat/+bug/1694371
        devstack_local_conf:
          post-config:
            $NOVA_CONF:
              DEFAULT:
                vif_plugging_is_fatal: False
        devstack_services:
          q-agt: true
          n-api: false
          n-api-meta: false
          n-cauth: false
          n-cond: false
          n-cpu: true
          n-novnc: false
          n-obj: false
          n-sch: false
          horizon: false
          tls-proxy: false

- job:
    name: tacker-functional-devstack-multinode-sol
    parent: tacker-functional-devstack-multinode-legacy
    description: |
      Multinodes job for SOL devstack-based functional tests
    host-vars:
      controller-tacker:
        tox_envlist: dsvm-functional-sol

- job:
    name: tacker-functional-devstack-multinode-sol-separated-nfvo
    parent: tacker-functional-devstack-multinode-sol
    description: |
      Multinodes job for SOL devstack-based functional tests
      with separated NFVO
    host-vars:
      controller-tacker:
        devstack_local_conf:
          post-config:
            $TACKER_CONF:
              connect_vnf_packages:
                base_url: http://127.0.0.1:9990/vnfpkgm/v1/vnf_packages
                pipeline: package_content,vnfd,artifacts
              connect_grant:
                base_url: http://127.0.0.1:9990/grant/v1/grants
              openstack_vim:
                stack_retries: 120
        tox_envlist: dsvm-functional-sol-separated-nfvo

- project:
    templates:
      - check-requirements
      - openstack-cover-jobs
      - openstack-python3-victoria-jobs
      - publish-openstack-docs-pti
      - release-notes-jobs-python3
    check:
      jobs:
        - tacker-functional-devstack-multinode-legacy
        - tacker-functional-devstack-multinode-sol
        - tacker-functional-devstack-multinode-sol-separated-nfvo
