heat_template_version: 2013-05-23
description: 'workerNode HOT for Sample VNF'

parameters:
  flavor:
    type: string
  image:
    type: string
  net1:
    type: string
  scheduler_hints:
    type: string

resources:
  workerNode:
    type: OS::Nova::Server
    properties:
      flavor: { get_param: flavor }
      name: workerNode
      image: { get_param: image }
      networks:
      - port:
          get_resource: workerNode_CP2
      scheduler_hints:
        group: { get_param: scheduler_hints }

  workerNode_CP2:
    type: OS::Neutron::Port
    properties:
      network: { get_param: net1 }