#!/bin/bash

# TODO(yasufum) Remove it after tosca-parser and heat-translator have its own
#     devstack script. It's because for installing them from the latest git
#     repo instead of stable pip packages.
# Get a customized `upper-constraints.txt` locally, tosca-parser and
# heat-translator are removed for passing tox jobs. In addition, remove nouse
# packages.
function download_upper_constraints_file {
    curl --location https://releases.openstack.org/constraints/upper/master \
        | sed '/tosca-parser/d' | sed '/heat-translator/d' \
        | sed '/python-saharaclient/d' \
        > upper-constraints.txt
}

# TODO(yasufum) Uncomment if install tosca-parser and heat-translator from git
#     repo.
# download_upper_constraints_file
