heat_template_version: 2013-05-23
description: 'VDU1 HOT for Sample VNF'

parameters:
  flavor:
    type: string
  image-VDU1:
    type: string
  net1:
    type: string

resources:
  VDU1:
    type: OS::Nova::Server
    properties:
      flavor: { get_param: flavor }
      name: VDU1
      image: { get_param: image-VDU1 }
      networks:
      - port:
          get_resource: VDU1_CP1

  VDU1_CP1:
    type: OS::Neutron::Port
    properties:
      network: { get_param: net1 }