apiVersion: v1
kind: PersistentVolume
metadata:
  name: task-3-tacker
  annotations:
    pv.kubernetes.io/bound-by-controller: "yes"
  finalizers:
    - kubernetes.io/pv-protection
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  storageClassName: general
  hostPath:
    path: /mnt/vol1
    type: ""  # Optional: Set to "DirectoryOrCreate" if you want it auto-created
  claimRef:
    namespace: openstack
    name: tacker-vnfpackages

