auth_url: 'http://127.0.0.1/identity'
username: 'admin'
password: 'devstack'
project_name: 'admin'
domain_name: "default"
project_domain_name: 'default'
user_domain_name: 'default'
cert_verify: 'True'
