heat_template_version: 2013-05-23
description: 'workerNode HOT for Sample VNF'

parameters:
  flavor:
    type: string
  image:
    type: string
  net1:
    type: string
  affinity:
    type: string

resources:
  workerNode:
    type: OS::Nova::Server
    properties:
      flavor: { get_param: flavor }
      name: workerNode
      image: { get_param: image }
      networks:
      - port:
          get_resource: workerNode_CP1
      scheduler_hints:
        group: { get_param: affinity }

  workerNode_CP1:
    type: OS::Neutron::Port
    properties:
      network: { get_param: net1 }

  workerNode_CP1_floating_ip:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network: public
      port_id: { get_resource: workerNode_CP1 }
