---
- name: install basic packages
  become: yes
  yum: name={{ item }} update_cache=yes
  with_items:
      - python3
      - python3-devel
      - python3-pip
      - git
      - vim

- name: install git-review with pip
  become: yes
  pip: name=git-review
