---
- include_tasks: basic_pkgs.yml
- include_tasks: set_path_env.yml
- include_tasks: git_config.yml

- include_tasks: python3_specific_vers.yml

- include_tasks: vim_extra_plugins.yml
  when: use_vim_extra_plugins == true

- include_tasks: kubernetes.yml

- include_tasks: ovn.yml

- include_tasks: devstack.yml

- include_tasks: setup_tacker.yml
  when: use_tacker == true

- include_tasks: extra_tools.yml
  when: use_extra_tools == true
