---
- name: install basic packages
  become: yes
  apt: name={{ item }} update_cache=yes
  with_items:
      - python3
      - python3-dev
      - python3-pip
      - bridge-utils
      - git
      - git-review

- name: upgrade apt packages
  become: yes
  apt:
      upgrade: safe
