---
- name: update git config
  git_config:
      scope: global
      name: 'url.https://.insteadOf'
      value: 'git://'

- name: git clone devstack
  git:
      repo=https://opendev.org/openstack/devstack.git
      dest={{ ansible_env.HOME }}/devstack

- name: install required packages for openstack
  become: yes
  pip: name={{ item }}
  with_items:
    - os-testr
    - tox
    - netaddr
    - pbr

