heat_template_version: 2013-05-23
description: 'VDU3 HOT for Sample VNF'

parameters:
  flavor:
    type: string
  image-VDU3:
    type: string
  zone:
    type: string
  name:
    type: string
  net1:
    type: string
  net2:
    type: string

resources:
  VDU3:
    type: OS::Nova::Server
    properties:
      flavor: { get_param: flavor }
      name: { get_param: name }
      image: { get_param: image-VDU3 }
      networks:
      - port:
          get_resource: VDU3_CP1
# replace the following line to Port ID when extmanagedVLs' Ports are
# specified in instantiatevnfrequest
      - port:
          get_resource: VDU3_CP2
      availability_zone: { get_param: zone }

# extVL without FixedIP or with numDynamicAddresses
  VDU3_CP1:
    type: OS::Neutron::Port
    properties:
      network: { get_param: net1 }

# CPs of internal VLs are deleted when extmanagedVLs and port are
# specified in instantiatevnfrequest
  VDU3_CP2:
    type: OS::Neutron::Port
    properties:
      network: { get_param: net2 }