heat_template_version: 2013-05-23
description: 'workerNode HOT for Sample VNF'

parameters:
  flavor:
    type: string
  image:
    type: string
  net1:
    type: string

resources:
  workerNode:
    type: OS::Nova::Server
    properties:
      flavor: { get_param: flavor }
      name: workerNode
      image: { get_param: image }
      networks:
      - port:
          get_resource: workerNode_CP2

  workerNode_CP2:
    type: OS::Neutron::Port
    properties:
      network: { get_param: net1 }

  workerNode_FloatingIP:
    properties:
      floating_network: public
      port_id:
        get_resource: workerNode_CP2
    type: OS::Neutron::FloatingIP