---
- name: ubuntu-jammy controller node
  hosts: ubuntu-jammy.controller
  remote_user: stack
  roles:
      - ubuntu-jammy/controller

- name: ubuntu-jammy compute nodes
  hosts: ubuntu-jammy.compute
  remote_user: stack
  roles:
      - ubuntu-jammy/compute

- name: centos-stream8 controller node
  hosts: centos-stream8.controller
  remote_user: stack
  roles:
      - centos-stream8/controller
